apps:
#  - name: calico
#    repoURL: https://projectcalico.docs.tigera.io/charts
#    namespace: tigera-operator
#    targetRevision: master

  - name: Hetzner CCM
    repoURL: https://github.com/hetznercloud/hcloud-cloud-controller-manager
    path: deploy/ccm.yaml
    targetRevision: main
