apps:

  - name: hetzner-ccm
    repoURL: https://github.com/hetznercloud/hcloud-cloud-controller-manager.git
    path: deploy
    include: ccm.yaml
    targetRevision: main
    namespace: kube-system
