apps:

  - name: hetzner-ccm
    path: cluster/apps/hetzner-ccm
    targetRevision: main
    namespace: kube-system

  - name: hetzner-csi
    path: cluster/apps/hetzner-csi
    targetRevision: main
    namespace: kube-system