apps:

  - name: hetzner-ccm
    path: cluster/apps/hetzner-ccm
    targetRevision: main
    namespace: kube-system

#  - name: hetzner-csi
#    path: cluster/apps/hetzner-csi
#    targetRevision: main
#    namespace: kube-system

  - name: nextcloud
    path: cluster/apps/nextcloud
    namespace: nextcloud
    valueFiles: values.yaml

  - name: loki-stack
    path: charts/loki-stack
    targetRevision: loki-stack-2.6.5
    repoURL: https://github.com/grafana/helm-charts.git
    namespace: monitoring
    setParams:
      - name: grafana.enabled
        value: true
      - name: prometheus.enabled
        value: true
      - name: prometheus.isDefault
        value: true

#  - name: kured
#    path: charts/kured
#    repoURL: https://github.com/weaveworks/kured.git
#    namespace: kube-system
#    targetRevision: 1.10.1
#    setParams:
#      - name: configuration.lockTtl
#        value: 20m

  - name: kured
    path: cluster/apps/kured
    namespace: kube-system

  - name: longhorn
    path: cluster/apps/longhorn
    namespace: longhorn-system

  - name: sealed-secrets
    path: helm/sealed-secrets
    targetRevision: v0.18.0
    repoURL: https://github.com/bitnami-labs/sealed-secrets.git
    namespace: kube-system
    setParams:
      - name: metrics.serviceMonitor.namespace
        value: monitoring
      - name: fullnameOverride
        value: sealed-secrets-controller

  - name: secrets
    path: cluster/apps/secrets
    targetRevision: main

  - name: cert-manager-init
    path: cluster/apps/cert-manager-init

  - name: cert-manager
    path: cluster/apps/cert-manager

  - name: nginx-ingress
    path: cluster/apps/ingress-nginx

  - name: syncthing
    namespace: syncthing
    path: cluster/apps/syncthing

  - name: nginx-spacemule
    path: cluster/apps/nginx-spacemule
    namespace: nginx-static

  - name: nginx-zahava
    path: cluster/apps/nginx-zahava
    namespace: nginx-static

#  - name: paperless
#    path: cluster/apps/paperless
#    namespace: paperless