apps:

  - name: hetzner-ccm
    path: cluster/apps/hetzner-ccm
    targetRevision: main
    namespace: kube-system

#  - name: hetzner-csi
#    path: cluster/apps/hetzner-csi
#    targetRevision: main
#    namespace: kube-system

  - name: nextcloud
    path: cluster/apps/nextcloud
    namespace: nextcloud
    valueFiles: values.yaml

  - name: loki-stack
    path: charts/loki-stack
    targetRevision: loki-stack-2.6.5
    repoURL: https://github.com/grafana/helm-charts.git
    namespace: monitoring
    setParams:
      - name: grafana.enabled
        value: true
      - name: prometheus.enabled
        value: true

  - name: kured
    path: charts/kured
    repoURL: https://github.com/weaveworks/kured.git
    namespace: kube-system

  - name: longhorn
    path: charts/longhorn
    targetRevision: longhorn-1.3.0
    repoURL: https://github.com/longhorn/charts.git
    namespace: longhorn-system
#    setParams:
#      - name: persistence.defaultFsType
#        value: btrfs

  - name: sealed-secrets
    path: helm/sealed-secrets
    targetRevision: v0.18.0
    repoURL: https://github.com/bitnami-labs/sealed-secrets.git
    namespace: kube-system
    setParams:
      - name: metrics.serviceMonitor.namespace
        value: monitoring
      - name: nameOverride
        value: sealed-secrets-controller