apps:
  -
  - name: loki-stack
    path: charts/loki-stack
    targetRevision: loki-stack-2.6.5
    repoURL: https://github.com/grafana/helm-charts.git
    namespace: monitoring
    setParams:
      - name: grafana.enabled
        value: true
      - name: prometheus.enabled
        value: true
      - name: prometheus.isDefault
        value: true

  - name: sealed-secrets
    path: helm/sealed-secrets
    targetRevision: v0.18.0
    repoURL: https://github.com/bitnami-labs/sealed-secrets.git
    namespace: kube-system
    setParams:
      - name: metrics.serviceMonitor.namespace
        value: monitoring
      - name: fullnameOverride
        value: sealed-secrets-controller

  - name: secrets
    path: cluster/apps/secrets
    targetRevision: main

  - name: cert-manager-init
    path: cluster/apps/cert-manager-init

  - name: cert-manager
    path: cluster/apps/cert-manager

  - name: nginx-ingress
    path: cluster/apps/ingress-nginx