apps:

  - name: hetzner-ccm
    path: cluster/apps/hetzner-ccm
    targetRevision: main
    namespace: kube-system

  - name: hetzner-csi
    path: cluster/apps/hetzner-csi
    targetRevision: main
    namespace: kube-system

  - name: nextcloud
    path: charts/nextcloud
    targetRevision: master
    repoURL: https://github.com/nextcloud/helm.git
    namespace: nextcloud
    setParams:
      - name: nginx.enabled
        value: true
      - name: image.flavor
        value: php-fpm
      - name: internalDatabase.enabled
        value: false
      - name: externalDatabase.type
        value: postgresql
      - name: externalDatabase.host
        value: 10.15.1.3:5432
      - name: externalDatabase.existingSecret.enabled
        value: true
      - name: externalDatabase.existingSecret.secretName
        value: nextcloud-db
      - name: externalDatabase.existingSecret.usernameKey
        value: user
      - name: externalDatabase.existingSecret.passwordKey
        value: pass
      - name: persistence.enabled
        value: true
      - name: hpa.enabled
        value: true
      - name: nextcloud.extraEnv
        value:
          REDIS_HOST: 10.15.1.2
      - name: redis.enabled
        value: true
      - name: redis.auth.enabled
        value: false

  - name: loki-stack
    path: charts/loki-stack
    targetRevision: loki-stack-2.6.5
    repoURL: https://github.com/grafana/helm-charts.git
    namespace: monitoring
    setParams:
      - name: grafana.enabled
        value: true
      - name: prometheus.enabled
        value: true
