apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb
spec:
  addresses:
    - 10.42.3.1/32
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: dns
  namespace: metallb
spec:
  addresses:
    - 10.42.42.42/32