apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: syncthing-pvc-longhorn
  namespace: syncthing
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 20Gi