---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: jellyfin-deployment
  labels:
    app: jellyfin
spec:
  strategy:
    type: Recreate
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        supplementalGroups:
          - 487
          - 484
        fsGroup: 1000
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
      - image: docker.io/jellyfin/jellyfin:latest
        name: jellyfin
        resources:
          limits:
            gpu.intel.com/i915: 1
          requests:
            memory: "512Mi"
            cpu: "500m"
        securityContext:
          capabilities: {}
        volumeMounts:
          - name: jellyfin-config-mount
            mountPath: /config
          - name: jellyfin-cache-mount
            mountPath: /cache
          - name: jellyfin-media-mount
            mountPath: /media
          - name: jellyfin-torrents-mount
            mountPath: /media/torrents
          - name: jellyfin-music-mount
            mountPath: /media/Music
        ports:
          - containerPort: 8096
            name: jellyfin-http
        livenessProbe:
          httpGet:
            path: /web/index.html
            port: jellyfin-http
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /web/index.html
            port: jellyfin-http
          initialDelaySeconds: 60
          timeoutSeconds: 5
      volumes:
      - name: jellyfin-config-mount
        hostPath:
          path: /var/mnt/jellyfin/config
      - name: jellyfin-cache-mount
        hostPath:
          path: /var/mnt/jellyfin/cache
      - name: jellyfin-torrents-mount
        hostPath:
          path: /var/mnt/torrents
      - name: jellyfin-media-mount
        hostPath:
          path: /var/mnt/jellyfin/media/
      - name: jellyfin-music-mount
        hostPath:
          path: /var/mnt/Music/
