apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: jellyfin
spec:
    accessModes:
      - ReadWriteMany
    resources:
      requests:
        storage: 1300Gi
    storageClassName: longhorn