apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: restic-ingress
  namespace: restic-rest
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    nginx.ingress.kubernetes.io/proxy-body-size: 1000m
spec:
  tls:
    - hosts:
        - backup.spacemule.net
      secretName: restic-tls-secret
  rules:
    - host: backup.spacemule.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: restic
                port:
                  number: 8000
          - path: /metrics
            pathType: Prefix
            backend:
              service:
                name: null-service
                port:
                  number: 8000
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: restic-ingress
  # needs namespace of traefik
  namespace: kube-system
spec:
  entryPoints:
    - restic
  routes:
    - services:
      - name: traefik
        port: 443
      match: HostSNI(`*`)
      #does not work with domain
