apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restic-data
  namespace: restic-rest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Gi