apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restic-pvc
  namespace: restic-rest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 200Gi