---
apiVersion: v1
kind: Namespace
metadata:
  name: nginx-static
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  labels:
    istio-injection: enabled
    kubernetes.io/metadata.name: default
  name: default
