apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: syncthing-ingress
  namespace: syncthing
spec:
  ingressClassName: nginx
  rules:
  - host: sync2.spacemule.net
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: syncthing-gui-service
            port:
              number: 8081