apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |
    user nginx;
    worker_processes  1;
    events {
      worker_connections  10240;
    }
    http {
      server {
          listen       80 default_server;
          server_name _;
          server_name  spacemule.net;
          
          root /usr/share/html/spacemule;
    
        location ~* \.(js|css|png|jpg|jpeg|gif|svg|ico|woff|woff2|ttf)$ {
                try_files $uri $uri/index.html;
                autoindex off;
                expires max;
                add_header Cache-Control "public, no-transform";
        }
        location / {
                try_files $uri $uri/index.html;
                autoindex off;
          }
      }
    }