apiVersion: v1
kind: Service
metadata:
  name: nginx-spacemule-service
spec:
  type: ClusterIP
  port: 80
  selector:
    app: nginx-spacemule
  ports:
    - name: nginx-spacemule-service
      protocol: TCP
      port: 80
      targetPort: nginx-http