{{- range $app := .Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: {{ $app.name }}
  namespace: argocd
spec:
  destination:
    namespace: {{ $app.namespace | default "default"  }}
    server: {{ $app.server | default "https://kubernetes.default.svc"}}
  project: default
  source:
    {{- if or (hasKey $app "valueFiles") (hasKey $app "setParams") }}
    helm:
      {{- if hasKey $app "valueFiles" }}
      valueFiles:
        - {{  $app.valueFiles }}
      {{ end }}
      {{- if hasKey $app "setParams" }}
      parameters:
        {{- range $setParam := $app.setParams }}
        - name: {{ $setParam.name }}
          value: {{ $setParam.value }}
        {{ end }}
      {{ end }}
    {{ end }}
    path: {{$app.path}}
    repoURL: {{ $app.repoURL | default "git@github.com:spacemule/k3s-hetz.git"  }}
    targetRevision: {{ $app.targetRevision | default "main" }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
     - CreateNamespace=true
---
{{ end }}