apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: ClusterIP
  selector:
    app: wireguard
  ports:
    - port: 51820
      targetPort: 51820
      protocol: UDP
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: wireguard
spec:
  type: ClusterIP
  selector:
    app: wireguard
  ports:
    - name: nginx-proxy
      protocol: TCP
      port: 8081
      targetPort: nginx-http