---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wireguard
  name: wireguard-deployment
  labels:
    app: wireguard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - image: registry.opensuse.org/home/spacemule/branches/opensuse/templates/images/tumbleweed/containers/opensuse/wireguard:latest
          imagePullPolicy: Always
          name: wireguard
          securityContext:
            capabilities:
              add:
                - NET_ADMIN
          volumeMounts:
            - name: wg-conf-mount
              mountPath: /etc/wireguard/
              readOnly: true
          ports:
            - containerPort: 51820
              name: wireguard
              protocol: UDP
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
        - image: nginx:stable
          name: nginx
          securityContext:
            capabilities: {}
          volumeMounts:
            - name: nginx-conf-proxy
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          ports:
            - containerPort: 80
              name: nginx-http
            - containerPort: 443
              name: nginx-https
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
      volumes:
        - name: wg-conf-mount
          secret:
            secretName: wg-conf-secret
        - name: nginx-conf-proxy
          configMap:
            name: nginx-conf-proxy
            items:
              - key: nginx.conf
                path: nginx.conf
