---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-static
  name: nginx-zahava-deployment
  labels:
    app: nginx-zahava
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-zahava
  template:
    metadata:
      labels:
        app: nginx-zahava
    spec:
      initContainers:
        - name: init-site
          image: bitnami/git:2.38.1
          command: ["/bin/sh", "-c", "git clone https://github.com/spacemule/hugo-sites.git /hugo-sites"]
          volumeMounts:
            - name: nginx-zahava-mount
              mountPath: /hugo-sites
      containers:
      - image: nginx:stable
        name: nginx
        securityContext:
          capabilities: {}
        stdin: true
        tty: true
        volumeMounts:
          - name: nginx-zahava-mount
            mountPath: /usr/share/nginx/html
            subPath: zahava
          - name: nginx-conf-zahava
            mountPath: /etc/nginx/nginx.conf
            subPath: nginx.conf
            readOnly: true
        ports:
          - containerPort: 80
            name: nginx-http
      volumes:
      - name: nginx-zahava-mount
        emptyDir:
          sizeLimit: 250Mi
      - name: nginx-conf-zahava
        configMap:
          name: nginx-conf-zahava
          items:
            - key: nginx.conf
              path: nginx.conf