apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-vaultwarden
spec:
  # run every fifteen minutes
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 2700
      template:
        spec:
          containers:
          - name: restic
            image: restic/restic:0.14.0
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              apk add --no-cache sqlite rsync && \
              mkdir -p /data-backup && \
              rsync -avz /data/ /data-backup/ && \
              rm /data-backup/db.sqlite3 && \
              sqlite3 /data/db.sqlite3 ".backup '/data-backup/db.sqlite3'"  && \
              restic backup --tag vaultwarden --host vaultwarden-0 /data-backup && \
              restic forget --group-by tags --tag vaultwarden --keep-last 7 --keep-daily 7 --keep-weekly 4 --keep-monthly 12 --keep-yearly 10 --prune
            env:
              - name: RESTIC_REPOSITORY
                value: b2:spacemule-k8s:/vaultwarden
              - name: RESTIC_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: k8up-restic
                    key: password
              - name: B2_ACCOUNT_ID
                valueFrom:
                  secretKeyRef:
                    name: k8up-b2
                    key: access-key-id
              - name: B2_ACCOUNT_KEY
                valueFrom:
                  secretKeyRef:
                    name: k8up-b2
                    key: secret-access-key
            volumeMounts:
              - mountPath: /data
                name: data
          volumes:
            - name: data
              persistentVolumeClaim:
                claimName: data-vaultwarden-0
          restartPolicy: OnFailure