---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vaultwarden
  labels:
    app: vaultwarden

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vaultwarden
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "vaultwarden"
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    resourceNames:
      - "vaultwarden-smtp"
      - "vaultwarden-tls"
    verbs:
      - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vaultwarden
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vaultwarden
subjects:
- kind: ServiceAccount
  name: vaultwarden