apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
spec:
  type: NodePort
  selector:
    app: wireguard
  ports:
    # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 51820
      targetPort: 51820
      protocol: UDP
      # Optional field
      # By default and for convenience, the Kubernetes control plane will allocate a port from a range (default: 30000-32767)
      nodePort: 31820
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: wireguard
spec:
  type: ClusterIP
  selector:
    app: wireguard
  ports:
    - name: nginx-proxy-service
      protocol: TCP
      port: 8081
      targetPort: nginx-http