#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jelly
#spec:
#  type: ClusterIP
#  selector:
#    app: syncthing
#  ports:
#    - name: syncthing-service
#      protocol: TCP
#      port: 8081
#      targetPort: syncthing-gui
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: syncthing-service
#spec:
#  type: NodePort
#  selector:
#    app: syncthing
#  ports:
#    - name: syncthing-tcp-service
#      protocol: TCP
#      port: 22000
#      targetPort: syncthing-tcp
#      nodePort: 32000
#    - name: syncthing-udp-service
#      protocol: UDP
#      port: 22001
#      targetPort: syncthing-udp
#      nodePort: 32001
#    - name: syncthing-data-service
#      protocol: UDP
#      port: 22017
#      targetPort: syncthing-data
#      nodePort: 32017