---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: wireguard
  name: wireguard-deployment
  labels:
    app: wireguard
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wireguard
  template:
    metadata:
      labels:
        app: wireguard
    spec:
      containers:
        - image: registry.opensuse.org/home/spacemule/branches/opensuse/templates/images/tumbleweed/containers/opensuse/wireguard:latest
          name: wireguard
          securityContext:
            capabilities: {}
            runAsGroup: 2000
            runAsUser: 2000
          volumeMounts:
            - name: wg-conf-mount
              mountPath: /etc/wireguard/
              name: wg0-conf
              readOnly: true
          ports:
            - containerPort: 51820
              name: wireguard
              protocol: UDP
      volumes:
        - name: wg-conf-mount
          secret:
            secretName: wg-conf-secret
