apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pihole
  namespace: pihole
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  tls:
    - hosts:
        - dns.spacemule.net
      secretName: pihole-tls-secret
  rules:
    - host: dns.spacemule.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pihole
                port:
                  name: pihole-admin
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteUDP
metadata:
  name: pihole
  namespace: pihole
spec:
    entryPoints:
      - dns
    routes:
      - services:
        - name: pihole
          port: 53
