---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: jellyfin
  name: transmission-deployment
  labels:
    app: transmission
spec:
  replicas: 1
  selector:
    matchLabels:
      app: transmission
  template:
    metadata:
      labels:
        app: transmission
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      nodeSelector:
        node-role.kubernetes.io/master: "true"
      containers:
      - image: registry.opensuse.org/home/spacemule/branches/opensuse/templates/images/tumbleweed/containers/transmission
        name: transmission
        env:
        - name: TZ
          value: "Asia/Jerusalem"
        command:
          - /usr/bin/transmission-daemon
        args:
          - --foreground
          - --config-dir
          - /conf
        securityContext:
          capabilities: {}
        volumeMounts:
          - name: transmission-torrents-mount
            mountPath: /torrents
          - name: transmission-incomplete-mount
            mountPath: /incomplete
          - name: config-vol
            mountPath: /conf/settings.json
            subPath: settings.json
          - name: state-mount
            mountPath: /conf
        ports:
          - containerPort: 9091
            name: transmission
      volumes:
      - name: transmission-torrents-mount
        hostPath:
          path: /var/mnt/torrents
      - name: transmission-incomplete-mount
        hostPath:
          path: /var/mnt/incomplete
      - name: config-vol
        configMap:
          name: transmission-config
      - name: state-mount
        hostPath:
          path: /var/mnt/transmission-conf