apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: secret-gitea-admin
  namespace: default
spec:
  encryptedData:
    password: AgAn4TOwM3CZss47nyGgCBmkAwEHiUviQ/GF1odksufwdCPmpUhprwrE6KUKUuHLwALHPtp2Qk5q+L698RcFIYsH8YBuXx468/osWHQD+reOhlvKvp95FOSBjHfG4LAvy2Za64BzXvTtz3TEOji+8phJoHTLhcuT1bKwrImtAujw4zjyh6xhj2g9h+EjvbG7ppMYntzpdwl/U7aZYgkjz7GXR2B0NYE1sCPqiSurvttnPVLTeTHFgf7UNseAjVK09y+8KZcrKCZV5tl/IlmL9fnmEQVK3Z//dmD1ls6SjbunxAmDGZCLMOQiCkTmC7qGG/2mff3+Q2KdElXB15/QVBkXbtzISDUr/8sRVT63MLf16r3FplQTogQy7InqH9DCOGn8iuRdc4+9Yg7A4ptzpGmhW25fQTKMHZFT3/2ZQpjOcOYpot7UkwEMsHaDoS+Fg8Y5PYVMZpnIgbIWIHYbrDLDyO/9v58llTlpdwbcIsHthPG0UASI5/56cB1sUp/NbOTS/Qx/GU75Tezp5fHgV5dBnC5cHheUeDYlOSQaJJgKk70ryCVGy3/7ChXb5kYNbMuEej3VndsHede832ZqO6wNEZrR27DS1XZ7PyMMIav332ZRGhhLuNFue/Wckys/FzPGwuu3BFElZUt1U3yoSKlGny44GMjXvzFd/hBMlgXkQhM7a0mxlUGk46ldiXhf0x1nveR2z3o8z7RL9x7B6w/ERyKHqDeQplk67I6dTlWKRcrCHS2KCw==
    username: AgAaR/huGnSPvoPWzFlyaghbTB9x51AY1M61QNVKzoYXng1gPn05SjHipv/+HLP8kX7DFZFYT1ffpxTeHDnply/jSVI51zdk6LuXRRResRBdBBD12x/08DbO9fE1y0wREuGQbRzgeRuT147+vKnrvCW8m2Y2jzWfWBibK60atCBlEig+8Z2buwNGaAtdisp8dt/VT68KcSOTbdimbXf2mO3XR/ypFIWW3SmQ205I/qLba3e58Uga4VZRDElYTFhUAFjTx8wxWKqkJUHQT8ULiIJyMDaOxzdSWYQQK4BkKfLXR9Z6j6eUbTmbd+i+Bc2nw9YqtPKW5eJQuA381SVzJthpsXT6k4B4FS7Oxdwb8NvzLGtoEIyMU2EBZwEiHynn2WrtCLLwxgHNzFLvLqPzeZgtCZT3GpOlsc9SP4wBS/uABDA8QWIUC/0mYRyNrQZb/R94ms60wRBY+/rjMcW0w0AT/YJN8cZCe5we8ouZhc1C7hW0mzC5J1rh7iVE6S8Vy4FDvpKd31nCjaoVR6B8Xj9QDlrkoQPfosYLlSwtlIx/YyvBoOSUtdJjo5mE/85ouA6k9icshHE2xNw/w5434RS2YZtdakYHGhU5sNUvviNqRNqepEW0j2VJSMGcJAi/iCJarGIhwt6NwgAXbiNCufNWuV70Q8kqMTkkwKRhGUN3RKm7+aIfSV+dwC34tuzvzUBxUBlrM4EfG/Y=
  template:
    metadata:
      creationTimestamp: null
      name: secret-gitea-admin
      namespace: default
    type: Opaque

