apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud-csi
  namespace: kube-system
spec:
  encryptedData:
    token: AgBGFk23GgVxkE3OYgGVpg4p3dBYvQW5xZKbNDxAf6PZQyXkWWUbdCWvBVU6DmS/cXnxY9zKCDOiR1bYFYDsuxLWqjan2E6GAVrP+hpEHImhT5xoQ5EDbvM6wFgGmHLPYEqKl6RTZOkX6HWZVlnJtUle8VERlR+s9uCDxf9EggdjDhhcqyrxuUSPsu5ULmwNRkgEv800SET0o46eqobGv1JWOsaxCrSBFDtm1o3Myh0rEBmHR0P4K8IjgSIVea44gGw3cqd8lFdAP7UoiLzhi7VQZnRDqR53wlpyeYHt+yMh75jeeOnb0mDRvQS1U8wyQ0fzOuMHENsypqADgG8UbE59y74TSzo+UUDhUpC6jmM+TDPaYxQFaPGy8QvagidpVT55mfuPzkgCzDQrvC1RRAlIggM273noDV6TkrIKfyPOfDTaIYf5JGKddtiEDoaGSQ8jl4pRxO0K7CnzrdxwKbxVFXKNcrk+VZ4jPJ3sVGsScTuAiD1wC5+dAQ+0X+BnY4IcxTfsx3h9HisMGXZYCR7yDMVxC65J+mhAuPRCRZyzpLWRZ6k7QBx2Umv05umCuIp+G9tkV6Ae7G9DWUy3RBJZcWOk3v+dUrjwWRWk2NE9zM8D8AJT3yiP3LqogULGzREZOMKMypI9yujCSmuRew1oAbH0GnOKzYoE/+8G10Jmn96e9CbIPU9heQr2e49dSBC8ay00jvPTlW/I6Q1VAlRieBbDejaIhxaxg9WlSoJivAYwH9/Tphhdv/IKFAPvXoXXJb32iPfPBLggosL3mENF
  template:
    metadata:
      creationTimestamp: null
      name: hcloud-csi
      namespace: kube-system

