apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    network: AgDYkuLIgBD1Ki6BrsYdOhC7iPUQtHJ+3gmJY8vZM9mAESzoxrgkutw+DZtmasCCKlryXoNYBYkuQ+cMmqmtlFJT9F2Pz+yYy28+HseSdtkc1RmNKsUdQ61BpF3cbmWB0IA2C+a9BV3pVGllO2DlR3rQcnoqeUSWd2jSHCKErylkRylhqsFdHYwDvwmMD3s3yH5cx5het3p1gSarUU9MK/FU9TgzRANTR893ilueV6T5TC6w1afYZPPWIG1IRBADBFy5KkJ5S8vvO8ukl3QFkZB6OlhkZ+JB7JW/kyyJvc7kTAUMUuig19s3Hr+Reov+Gi+IoTuoamdslLiD2KrO2BNJQZhguj+1A35ISkuppZJmBjmVxd21QaKCTgaKKe3gDxboBrv3Zxc9p9AjGmLwupQVT5izuw7CGC7aARJJDr7wBthXscy5DYCmS0PZ160olHTF+PKIgOxZavytB/H/cE0fRB6Knzd3GDzlAR7oeI0EZkbdGeSllbsYnBYgC9x519nxCiNow2rnqjXqvG+bHGCtdPOcAAXL2gc9H2qlaNisC3mn3wwYJBwdfjlrpjjnTQHB0ShPq5D8+5QJkGAElXxkmNRJVjI6JdO4YtZyDReHmxB6mKitR2PyUqIatgL/PXUqf1aEndB4Sc3vL1GVinTsn9kNIya/7pGkRvD/jcDgTF30eXMFmiLDSgGn43EfwGx4mvFaykq8GQ==
    token: AgC8CvEmlUQ+PA41LTsTAXARDee+96kHeuHFMWTjUviMj03Dx6h9N/uHAHqEamUTPbrBmCN9c9jE6BCdbSfO8ADGFTuP5kBgKAGDqEA3RRQjsF1zD4ZBWdM1s/Clx1Sk7N8lxJpphmrmAorUcsAJqdJXCJNqQcXAxFuOFjcnxuo7qxqvJhRnoQ8Gf3kv9w8K7MsKgyzPQlOvogGcOmHwdctPZRkh2VvorcELQQQOIe32sprgJQDstS1bOdgEo12JVSi8fvx5M6XtxErQ6E9JzGxHwOOBdOEI7tA9GjnF6R5MQTnLWPN2/bgue4COq6hEsH5O+mz56EOuOktuinX7sVCCJEGjweyDKglpaoy+WJxyX2JkqO1xik2KDrHjod6VUlzSIfObl6zeI9DWRpqhuKWldeRIYmXIgItVK9ivWM/j4YDhqThzL1hg+ZYi7ho6SC/1pmsDtc48s1AvlPC9U6PeaChW2J5N6JYdVoHHp6olDQrPcx5bAlxJKubQu1+0t7I9EJnfz0SwIPQmYUhaSikfscDhm/CK9PyUrgND2FEdmBr0DyAO6eYt44WoOkteHILGzbEXwhQMZQ/UZp06782Lkisu3UgIxHITVl+33P1rD22AyPBPuPyIaimLfkLQNwgOHebUzs9ynQtiojcWInP3ClbuZDBb4acLxBMAi7DOSauKuUtRWjKy+GVnR15cg4O/qox0N6deX7kHzlzX8Orzs5TZrQOJMJFEhrjGkMj1ombll+4TEGX6LsiheQFYQeRMesR0LodSQS+OHvjFvN8T
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: hcloud
      namespace: kube-system
    type: Opaque

