apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secret
  namespace: paperless
spec:
  encryptedData:
    paperless-db-pass: AgBsPNdDoZq6AZa2V50TgSA91ZEyMexrarRRauOGwJQspjSqf8//qkwySlgWxg3pfNRLEI33FPx8445XfZBJC8A7lWhC5TICssBcHrsQ8Yi7MuP9nnSQKAYeszV+e9K6qLa27OcgBBJht4jWejItRkf4gsv1evQ1k4CW5okBhC7CoQ3Ku9mB2ZRa2azsYKTTHtQKxN3E8xyjATsga5YF1R8E/JR7MCmXtLib9b5FmO0QcLzpjDso9+QvNoZAakke8P3cRkRUVvovJilSD9siIXco8ZUVf+JcIEJKPcezTE3+ZWhL/Ce4hctIa+6TLgfOun1+NfVpbII2y5BNTl8fzZVN2VaQ+O9wKC8GloB2oYg2Uq/0eRf9LCn3NvQVp8R8U3+NKV4SJ7LZXUmTZqGAe+UTVb+UX0Um5qkWEFyghh1Ohyjlsnhjku7jlnPg+hBaME3zNCoMLKyBnSfCGsS34NwM6o2Qm65Na8bBAxnOxY6dAwIGImqbPnvONWu22YrmoHDRlnRa0kbOrmvEoJmDRBNWjcUz7NX8Y8J30aMbqEV+4NmtA0/A61BpP7gJ8JwwfMSjhtNMBm9G1pjP0+JL/j0bIlEYLG7hHRsi+mdt4bXdyKReU7ZyQDdv9VJdo0a3zTecxRQxP5JRER+rmbWtpghQrPwRphBP0BAwcHjZz0FXwiBQIarRZZVUkF5gx2ku80jWoBs5UgRRdgm9l3zF51011fVAqwQ0Tw==
    paperless-key: AgAQ+KxhH2gohmw1Jz8IHBK/42Uqv/FFFqvfSLgTvO7QCQXiemnVDIusNr4BwQUupzaplT3A4mlMsH8+tZ5wxXDe5yoNN328AbFQVwmdJ+e3KDkrplkGTOmIRSGYCvVdMldDyjl5HVVoItF1NaP8hg7P/NYYUC1wZmPGuhyop+8p5wE+fEXtxEqowyx1tDhfMmb5uKfgk8OP+Co+78GLw7c6bkg4nWmpIMIhjtaN9BAI3WOpgH4eSyNVsjaNepkBR2bXFzYbFylatRu6Cm8UZrElIY/Evppd/l80pk8YZQ88kX9WTVLD9wsTUFggx8d3cPKDrqelIYCl99EAq2UiNNIZAos6vsqwdC+NYERJn53pmGGj0+XzYeeYmF2/yYkR83XpKQ3jWA8JowgWS5MikwDTL7cf5FA8qakx/GdH3odHdYE4zDEETFxnycUMvsakrVdB06F+1jnUs7EDGNdjOB+FEf639gHXatxv2osQmAQFPsW51ioPqNHXRsLXaITFYS2gTKLrNjy9I5MdpcHxk1b5FbDa+HyXGgpK4/5AklEsiNGQLRk5pzpubSKAurFMLV8mmMWwJn7BwHYUfp7sgTyHkjHXoBq4cEmERKtesl2GjZci/y/JbsD9yuLo03nR8WOSL+I43KQPyRd//sysw0sMzNijytOHAAZY6YaM3+bRvPe1eItM1//oct9872Tbg0k/zD7lsiVYHcbgSTjgJJAqvitVhSCfp4LWDmaVNIlLiGFbNjeIMpgFddEoxGIBem+Iq54K/Zw8YHEB61nyk1io
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: paperless-secret
      namespace: paperless
    type: Opaque

