apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-spacemule-pvc
  namespace: nginx-static
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi