apiVersion: batch/v1
kind: CronJob
metadata:
  name: iptables
spec:
  schedule: "*/15 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          hostNetwork: true
          containers:
          - name: iptables
            image: opensuse/tumbleweed
            imagePullPolicy: Always
            command: ["/bin/sh", "-c", "--",
            "zypper in -y iptables; \
            iptables -A FORWARD -i eth1 -j ACCEPT; \
            iptables -A FORWARD -o eth1  -j ACCEPT; \
            iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE; \
            iptables -t nat -A POSTROUTING -o eth1 -j MASQUERADE"]
            securityContext:
              capabilities:
                add: ["NET_ADMIN", "SYS_ADMIN"]
          restartPolicy: OnFailure
          nodeSelector:
            node-role.kubernetes.io/master: true
          tolerations:
            - key: "node-role.kubernetes.io/control-plane"
              operator: "Exists"
              effect: "NoSchedule"
          - key: "node-role.kubernetes.io/master"
            operator: "Exists"
            effect: "NoSchedule"