---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: paperless
  labels:
    app: paperless
  name: paperless
spec:
  replicas: 2
  selector:
    matchLabels:
      app: paperless
  template:
    metadata:
      labels:
        app: paperless
    spec:
      containers:
      resources:
        requests:
          memory: "512Mi"
          cpu: "1000m"
        limits:
          memory: "512Mi"
          cpu: "1000m"
      - args:
        - gotenberg
        env:
        - name: DISABLE_GOOGLE_CHROME
          value: "1"
        image: docker.io/thecodingmachine/gotenberg:6
        name: gotenberg
        resources: {}
        securityContext:
          capabilities: {}
      - image: docker.io/apache/tika:latest
        resources:
          requests:
            memory: "256Mi"
            cpu: "500m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        name: tika
        resources: {}
        securityContext:
          capabilities: {}
      - args:
        - /usr/local/bin/paperless_cmd.sh
        resources:
          requests:
            memory: "768Mi"
            cpu: "1000m"
          limits:
            memory: "768Mi"
            cpu: "1000m"
        env:
        - name: PAPERLESS_CONSUMER_RECURSIVE
          value: "true"
        - name: PAPERLESS_REDIS
          value: redis://10.15.1.2:6379
        - name: PAPERLESS_OCR_LANGUAGES
          value: heb
        - name: PAPERLESS_TIKA_ENABLED
          value: "true"
        - name: PAPERLESS_TIKA_GOTENBERG_ENDPOINT
          value: http://127.0.0.1:3000
        - name: PAPERLESS_CONSUMER_DELETE_DUPLICATES
          value: "true"
        - name: PAPERLESS_TIKA_ENDPOINT
          value: http://127.0.0.1:9998
        - name: PAPERLESS_TIME_ZONE
          value: Asia/Jerusalem
        - name: PAPERLESS_DBHOST
          value: 10.15.1.3
        - name: PAPERLESS_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: paperless-secret
              key: paperless-key
              optional: false
        - name: PAPERLESS_DB_PASS
          valueFrom:
            secretKeyRef:
              name: paperless-secret
              key: paperless-db-pass
              optional: false
        - name: PAPERLESS_DATA_DIR
          value: /data/data
        - name: PAPERLESS_TRASH_DIR
          value: /data/trash
        - name: PAPERLESS_MEDIA_ROOT
          value: /data/media
        - name: PAPERLESS_STATICDIR
          value: /data/static
        image: ghcr.io/paperless-ngx/paperless-ngx:latest
        name: paperless-ng
        resources: {}
        securityContext:
          capabilities: {}
        volumeMounts:
        - name: paperless-mount
          mountPath: /data
      restartPolicy: Always
      volumes:
      - name: paperless-mount
        persistentVolumeClaim:
          claimName: paperless-pvc
