apiVersion: v1
kind: Service
metadata:
  name: paperless-service
spec:
  type: ClusterIP
  selector:
    app: paperless
  ports:
    - name: paperless-service
      protocol: TCP
      port: 8081
      targetPort: http