apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nextcloud-nextcloud
  namespace: nextcloud
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: longhorn