apiVersion: v1
kind: Service
metadata:
  name: syncthing-service
spec:
  type: ClusterIP
  selector:
    app: syncthing
  ports:
    - name: syncthing-service
      protocol: TCP
      port: 8081
      targetPort: syncthing-gui