# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-4.1.1

# NOTE: If you generated this yaml from an unprivileged and rootless podman container on an SELinux
# enabled system, check the podman generate kube man page for steps to follow to ensure that your pod/container
# has the right permissions to access the volumes added.
---
apiVersion: v1
kind: Deployment
metadata:
  namespace: syncthing
  creationTimestamp: "2022-08-03T19:24:46Z"
  name: syncthing-deployment
  labels:
    app: syncthing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: syncthing
  template:
    metadata:
      labels:
        app: syncthing
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - image: docker.io/syncthing/syncthing:latest
        name: syncthing
        securityContext:
          capabilities: {}
          runAsGroup: 1000
          runAsUser: 1000
        stdin: true
        tty: true
        volumeMounts:
          - name: syncthing-mount
            mountPath: /var/syncthing
        ports:
          - containerPort: 8384
          - containerPort: 22000
          - containerPort: 22000
            protocol: UDP
          - containerPort: 22017
            protocol: UDP
      volumes:
      - name: syncthing-mount
        persistentVolumeClaim:
          claimName: syncthing-pvc
