apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: recipes
  namespace: tandoor
  labels:
    app: recipes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi