apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: recipes
  namespace: tandoor
spec:
  encryptedData:
    postgresql-postgres-password: AgBOqdbOKWh62PoTLeGab6XnUc5obLhWkqqWq4A9DSimgC6dxvmN9eaGn2E+U24aAniD+qZ9GEzZ6ACP/DucTuJZS9mp2sjaORWQOh16rqVu1OoXQW19Z2PMaOnGEE67PnS4LWbyHFE8AYMpwxKUTmbNSCiEJSJVnWl/8zu6UC+DXidSxcJdkY/tqVOpShyNq+Tt5vClkU9/ks/5MUGtI9jxq8KWuUIawfzA6ebQT6z512JtGFHb7NyzZTjHpJXrClU9zWZ69uCEMOolxH/sx7PcHzgAc4J3zwMFk67KB5alOhGPjayThT9Ybt+F66oC0SzmmFf6w7KsnYf9QjLknwpsEKOqLu6fy4WyiyEo6cAx5Y2b47Y/Cd8Q/EBpKVQxBpZamaC8R/Xm69q8NYjYbdjBEIEr0QPOrLbxg4cYGdUHM9/aR31eYFTAk6YxbcFJ8Ee6E5ZQ7TiwLOKmdDba5yGFK3zo1rBUQm+AfUhPrvmihtCAPH5enqvPBUZI3kpMnE4bTwGCaD1bG1JGs+sCHjLrft1LJk4C4TaXmgWKvgd0RWsy1kvFwVF/cPfGblBxp+EdFyymiivSNBt1AEZi1kEcEKyGwAxUOv6L+/BzHu5NKVKiD2a8B6JCsVVN1K63ut0YAnQtGNs11YyIkWJ0vuCRzdpSCR2cJHeXwFGcry2dzLgbSjvfpejC2qGypEXQlkodxIV/qbnZN4dVjFPUIT7rFudfGo8QBLA2SQ==
    secret-key: AgACfQ4PncNwuhsLAx74k3elr4nPWoZJLIWBP5/SGRtdOdZn78HmgpV/FzKIXRCo7NtcWmLFLmwN99AZf+wm/pPNHHps0ZhwwyCptT2ZTWTgCqsJSl/N72zsMb9Ar+RYUqYygKNj7N2kBY8nlM/zuLbRQkmoGB9LjNn9KmsD0iABsYgnA7mSAI7pSOT0Kfys0gPcvYgeIX1Nck9B8FkV7ED8BZpEzo8ILTdJ5CVC0ZkOxevp54rh26qgZvyWD7CTI7wPslz2ZuZTeVy3uCp8gDy+1CvQTcCQds+fERRuxvjhDl/nkdmGiY29G4H/Vfk4Nc3CMUM2S/P1Fo7cFLJPSeYvP+6j3evwIX06eQ9VHSCiAZb5kt25rn1OUNs1vKT8/OdDmvmmzVulJKN8UambKwXpZDIai/ssKH4+8zCvOcD13jjRykzhNmF8TXQAX/YYmYRkwf7nLgguf222rgm93bUbaghNlvxHTzm9TviRHcSEWYvdiT24DSEeltPrspxM1nnnc8CHcuSohRaIMJSeoIfV3ODZ5O7venzHW3SynQ7P7d96x9kAue4lh8NpdjB7oi2BbZTdwTEZwXtK6i+ApI0LfbmFrcPkLlTIraMDXO8zn/5eHmc9XQH7xLtyh3mIv4K2baeftMKoJ6A+R2Ww7pOGHlNpUcJdQ17QPqr5dLMkmz3AKv7MFQy6GycxU4JihXSipoEOGOk1BjINtzk1JYnPCExaPAhFc0xHoPP+6DdBlbWHC32aFLHwDo0HeF5TOM/QgSbpRrGBZIPwqs1JLKUi
  template:
    metadata:
      creationTimestamp: null
      name: recipes
      namespace: tandoor
    type: Opaque

