
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: 10Gi