apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: paperless-pvc-longhorn
  namespace: paperless
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 10Gi