apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: paperless-secret
  namespace: paperless
spec:
  encryptedData:
    paperless-db-pass: AgCU0v0R1Q/u6VO5w8EzO6nDJ+XLfJ9lXIq7Opx+9DeKihkLGGNppUYxqxQRJmxdADXE88b5XROsK/SQhN7o4MsnU8mQ8PKhQt68z1/L9EhmzMCIerI59N50MkChn+ssL39MzaXNFasKWF9ChcvG/4v+ZrT9qddCTTUP3DMsYR/Kap/WQEpYYGb6srrUYCEmKhff04POR66b0P6sT3sOcFs5y+Jbf/ugKlEBD+fGbZZTejz7xBa76q7RVazCkE4O2MixOpvcm7QAEX7W+PNnpJUowCTbDfcHtQb+jK/BEhQ4BZAqAwNZvRi6hrtU5KOvg17Y6kKexojrCeO2NaDac4elyHas+pdFdl3sr7N39MHHubKlBZKfofmbTZAlImuaN9gDMDyQ3L5JEr7zQVXDC2U+Nz4lDxW5mzBjJ6bCGqPWuRfGleHN1Q8ILfyDwMF1rS1afA59WZ+2bXSXxjJV706I+x+feqrPMKhrNd4t/c0iUBjyFAf28MdDjlAurSxpMAaxrhB26j/OdEO/WBeeCY1UgbJWWU/Y1nfxGIkN5X/EIBBKzFEma5V59Daqih2q2k/5WrAofZW7DNtAmXQ+s7kLvmnovXubndWA5rsBxaM+f6lYtE1xHtCYtOmgQrYyBsYVZ6PB5/1lI0oogfGNg/jggu4wkaHnKXTrvfnRivmmQsujLszwOOB2plXzmR3PtlDmqnuj7kOL8q54W4qjEbnWzttmpYEk6Q==
    paperless-key: AgBO7o82NI7i6KRMdhZJZ7BNA/BJRtB472LNTm7mSeG399v1y9BHvOP3EIlLWLpNdjQnVDF0LAwDneXA7gB5ZSGLBbzMn236h6SIgXJY1kC7+TTwLCaxS00eXA393864x2Q4EfFdO5s2DjkpvWiVGcF1TPS2PCY2aqmy8H1gV5uNtwq5DBNn8aw8LYa6jPNsVkwXlj5AEF3/yyi/4/kXwic5OirK/e37+llWaDcxt0z8Rro/oRkuDvgVVozyPCX8Cru3rC01ZJOqAG1HMj4lxf7dEIfpxKeqgqigidd+MnqcD/tnCceAMgrS76trDJQrzcjYV+Ij8OvP5Xg7b7db2cPzeCsONyYiq2z3Xf0a5vRD6CIRSx1lbgjixM0QOjHFOxsnE5tVI3BmP4eqiVLLKM4kDQJYpiHfRxydSXTwLB7q239b4PyBqEZfXRJTu0pzDY3gknjffWgU6XrT7fTYdZTp2diBfec4DECpuZmacZAA6Fh3LTEkKN6LQ6MmzTyIxJfUrZEbA0eZcG55RYYvIXfe5xb8dgJOr4gkUAZ5h1KLqq5vIen805XxHp+X68DPUbdAXT8CMnZ7F2BOdz0cXi6Vm2CUvJovOjmjtiLcYxcgTap3v0BPlrKBfqnBXxUgirzLMMH3LAUlj/41/WBPfgY5Sz0/BfQsNBYkY0N08zk8mbJ+acec9tApF9tuWkhHqdT4UjBT1+81Vi9G1S3+FPJNysc0f1xpSUWdbWFTxoaHYhkO20ZypwEAdQ8l3+z4WSNT7LNup7YgqBvLioRQO5bD
  template:
    metadata:
      creationTimestamp: null
      name: paperless-secret
      namespace: paperless
    type: Opaque

