---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: nginx-static
  name: umami-deployment
  labels:
    app: umami
spec:
  replicas: 2
  selector:
    matchLabels:
      app: umami
  template:
    metadata:
      labels:
        app: umami
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - umami
                topologyKey: kubernetes.io/hostname
      containers:
        - image: ghcr.io/umami-software/umami:postgresql-v1.39.5
          name: umami
          ports:
            - containerPort: 3000
              name: umami
              protocol: TCP
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: umami-secret
                key: DATABASE_URL
          - name: DATABASE_TYPE
            value: postgresql
          - name: HASH_SALT
            valueFrom:
              secretKeyRef:
                name: umami-secret
                key: HASH_SALT