apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: umami
  namespace: nginx-static
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: umami-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 50