apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nextcloud-db
  namespace: nextcloud
spec:
  encryptedData:
    pass: AgCmJTGBbl+HE8e6A2gXnZKbuGBBsAa7TMsKmcjXFKtru9Dxhb1f0XLWF1z7YDwGGGVfBuZIHMDoxRHu5nluLHShEkm0zYH4dVWkuKH/vnK9jynNi/xEsN66opdfuy9JkMpTXf2zpf6QCHboF5jf624/rESKg3prbIvf1EXiNsqbutDJygXysjC9YONzCCWLBpA9xN3qCnKnNAvQspuqlLc8tfMB7jkrEQMOIRkYui7N9xlcTbpQ5Ag0jikBi9Lk3PoSK2xQXztKF6ZF4u/Nf+cubsKVPwDITnAW2/+Vt8TGYeHeH2+1H6ZxEhlfOheNL7plbA0ZxhdM8dMu7L42gC9Ej04qF5EvG5WlZKuyP6YOStrlHULN5t1P+Im9KhPLCrXgrWjUZY4S+6MTOdDhzI32cJJxVWt9otlsKjr+Wa5Zo/c6XZdoMb28XB8xHJDP0polid6Ef3HjRUlBSpKnnK+xX+nHHShDyBQg/MQInPkFhiON3o5gWe/S+a5ZORFN/KB8CX9mjM45OdIkJu/nPoRR3flrcuXq7KHQ3s3qOP8zZb0fXnEpe72f96uEwRbwx+nNZyOdQzcRHjjsIhcrCSUnR34UFbR52uBqLhyz21QytBApVZTjAmRZ1M+vCqd2WRrleYeUQXl56+/+AZ92hmmXGNbAPvUQM56RNxEe2ekRic4ODn4cVhhFxo2l/uwEdH3dNeFyeMU9jed/5B+IvolJUElPGdZRqTs=
    user: AgAnV33KvTuM8S5DMu4jHvqA69F35lLJrc+n7S/s8iomHa4Vnh2vjgzpy1uEWjJMSwReoz8MSEOEETaFij44wlEN4WCDLL4CfGsXOMa/pXicvnfZ/+sNl1qEo8vECSVHD++13oXdxKZWq8+ZCA+xe4D8nhrmQOAGHyNnhPT4TJwpncmY/yOpWMYO2QsOWom9niEwws99WsOxjFlAtkH3ipHY5XhCrtAWHiz4t/WNOAdj/Aw6d2W5Dms2WJIOYZ2Jj4Oq2gfETFYVFVQvTDCPumrJmNHyDRDtIdvuVEBz/xA1cvuLCXrtrIdzeOoGhLXs+JqVhqa6sp0aK4EZlElsokLHPhjhS95QEerAqPsuKmLZIlxGeXwOUxguK6q/SQ/RnHuuIY77aRiOasB12X/ij8BbeqIM9Ao+143Xj3YUCwfbr1vivjxG431lxaHv47X8WhbHvqhqH+ng7rw6NnVB3O6K0FMbtFUsjpepzTzoxhnhmPHSm9IDZrHHQIajQrKrdu+e52Ya7t0Bl+eMM9mn4oLiHyFOD8ydLNFqOWROH+rZc3ZL/Jwm6hNlLWgs2EeHdQIlBUDBa8d1GGMS/XakoXe11BZRWdvV05O7NnG+AXLpLNWvS71n0lOCznW6fcsio8goQdptez8Orcn2bHvV55thpn3jOL94BMINFoPVAbQn7PkpFhCFpDCVvVPEQP6XxQvSx4KRr+inwwE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: nextcloud-db
      namespace: nextcloud
    type: Opaque

