apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wg-conf-secret
  namespace: wireguard
spec:
  encryptedData:
    wg0.conf: AgB5qg4a3wfyiLQB9djcilgHDGlJIooy/C1N5oPfY2DXCKFCUyYoib59PKfmvSxuj1A6JePMsXxIR24u+8oynioX2RvtnCZVlqmw1ablgGmKqW5c06f1NkrnCLF2G+VNw3kmYxOyS8Nr1Mqml7bf5RFeR4qfsphwYUmOk54dk7UcVRPFgnYCecpDxpm5DUrzCsA9rSnCaHPf46TFjy7wd+jNa+XkZtDpiRPyj7NsfnsEiuHtdtJuXvss9KLMxblBTQGKYXdfxVIqFxXPxPG7FGK+nJVBQ44cVJGIKErGNJQWIubdXvz/twlWGJ+ml9DhZ4PHL8/5slHvTfo2fipzEWlD86q0KEfrHfdPdNtd/nkUDSR/e+DDhruI7TcXDfXL36MPEU8b7XF0tfRCkBfENaUOBtlllFAYzOjFTCJ74ayllYjqjAo5n0znwhOjNr6IltoMknZz06TUEVbjGscbh4QKqL4XPDzxyxHrg39nq3bCCwPZoc04fs4ukxvs0g6UxLqLkl+WxYihL0p8BKdCJ6ql4rNXPzX6mXj9dAPSE//IM3Y4YZtyBvbhGiYDKjeqDRiRg9X+l2m0Sc1FtqQhnW8/V/kZQuQv9azqojZkhRM9TJKwQmVMBrG4Uj2Xee1OmNIwPybwNbJJCIW/P3mTsJ4h8gqCXZ8wvzXYK1J49Fqf58hw+9EFM6oO22lHMdL85436ON/dgamjkzamDSGU3UxASkPf6napgt7Yr8e/mcjknLNpdCIGJ1Ur/VPqgL1VySwqsHAvr6Odh3IzIfe7kwbQetD423KlbRBl/gknxjlxzfIgkyXS6R5t6yNUH+9MiSoGCW8aIkpk0ZutYLlfVw3rJVOMwQysdqEJYmWvmFeL9qh6VB3TWxXgmWVjLu824VIiAmonQJRW85/sKQZ+rCySew4SN0VZsM6jR5oLGLVcBC7y6Eo+5JF4KCMkXDnCeIP5Woe7GbsQX5uXBi8yquXpe69nXYqanx9ylTEEMsvxDxyRmxJkgQqg1LcUz2XlmrYlzGOFnMmVOD6a62Pviun4R1fFmYYcq2eUiExDfVk+HzieN9nMfDtcG2U0m9lQpOroxkxXaKbkFFVWuQogtzCdBbXRVMMHRkvyd+x2z0azjjltv73vkeFKFjR+ZqpwbsBCAPJvotVMVcbhpLvbhJTvnSAvewdpGvDZ1AZ6ZjJSFQan2UySCH96AJFshaXsqGd5TMf/QDxT9kNyIbPN+yIiRDdqxbkJwwPhJKtasix+Ry58NFyCU1G+Q4eirsOBZaFUmBigaWkmjwIFOS9EuIbscw1d/0g6sF6xYexAf5Raf/wQp+eP/i6m/EkAnxlB/K1iFKyV3rfDmGbN0gvMtWdtihWGB5CAWb4/FKsB116A+ts8M2Cv+KJ3k5w8OpRIj4s8dUXuYSM0nyFHm4k9fRHLYpR8Wu/5RDboP3AmfMMqf+R2R2MXBwq/GCbSprrkaLx1Ch0GPv7373biFrOYq1ZUnkH4jD8Ttqi5/cs6QoSd//syLgldAzsh7A==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: wg-conf-secret
      namespace: wireguard
    type: Opaque

