apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hcloud
  namespace: kube-system
spec:
  encryptedData:
    token: AgA9Jcv4UBVFiTdJI9Huaw+Bf8N8eIG4csDxGUhCYWYGmrW6cMwQb8X/laImabfKOu+5TiTRGnEDjd3z0WBeKTJS7qF1NSZq6F9KJotV9xUo6m5YKzTecibIM4affQLSMIRkoC9lNjlada+kR3DWTQCJAjrSQF63QnjdMpAcPYAhJRBgO0OjwkiD2UqUjOqma8nxZK2055t09uWQAESduw3c0A9A5Mg/MGgaYIr0zGCqLwS8U/59pFSxhPXkndEBGpkhI0b2qDqMamCzNh9z+sJL1fLiEI/msug5MrAUJpp6NMZX5oMONEeL3pPpgPIje3T2xzCuhooaEbofO5Ka7w0+sbPDpUuryt6fMFcL8+8eq2UppQNYSwhtTaXmHb5hNsOlYKBoBGp4nD1GLt58uOH2t4JMX9L7biMUrm7yIKUbLi0f7lmruSYnCPv52LTtFVKIZ1ypmAnxCJI2Yle2kQ0ATPGBGf5j/I4eY+35NMJXwSgv3zSFb0TJ+X8Fw1i+nTUA19ZTu05G6w7zLopo0fAP14MXvcIie8sXeVs38eM1cVVjgh7fGp7RGs7mchofd+oYaRc5CGwlq/HwxK4vqQa/Isetbt4t4pmKCa/0xZjeUvI7KJChDJVBjCb0sbZiiYHVB+nbWdSep3djIK0V8VoUL/Dz/P1t0094b9cVr7lVT+ZuufhHv+AyRxTnyPCt6iubtttZ0Oy09CQ/UDX9W1JXUB9RhWc+CquT6tFpJRwmeawI0uKOmjt7OTOwN/86jsEwlXstw7Av6F+h/RUEYVpy
  template:
    metadata:
      creationTimestamp: null
      name: hcloud
      namespace: kube-system

