kind: Service
apiVersion: v1
metadata:
 name: jellyfin
 namespace: external-services
Spec:
 type: ClusterIP
 ports:
 - port: 80
   targetPort: 80
 - port: 443
   targetPort: 443
---
kind: Endpoints
apiVersion: v1
metadata:
 name: jellyfin-service
 namespace: external-services
subsets:
 - addresses:
     - ip: 192.168.10.10
   ports:
     - port: 80
     - port: 443