apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jelly-ingress
  namespace: external-services
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - jelly.spacemule.net
    secretName: argo-tls-secret
  rules:
  - host: jelly.spacemule.net
    http:
      paths:
      - path: /.well-known
        pathType: Prefix
        backend:
          service:
            name: jellyfin-service
            port:
              number: 80