apiVersion: batch/v1
kind: CronJob
metadata:
  name: test-mnt
  namespace: kube-system
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 60
      template:
        spec:
          containers:
            - name: shell
              image: docker.io/alpine:3.13
              command:
                - nsenter
              args:
                - '-t'
                - '1'
                - '-m'
                - '-u'
                - '-n'
                - '-i'
                - '--'
                - 'sh'
                - '-c'
                - |
                  COUNT=`kubectl --namespace kube-system get pods | grep test-mnt | grep Running | wc -l`
                  if [ $COUNT -gt 1 ]; then
                    echo "More than one test-mnt pod is running. Exiting."
                    exit 0
                  fi; \
                  if test -f "/var/mnt/sentinel"; \
                  then echo "mount exists. uncordoning node and exiting"; \
                  kubectl uncordon $(hostname); \
                  exit 0; \
                  else echo "mount does not exist, rebooting node"; \
                  kubectl cordon $(hostname); \
                  kubectl drain $(hostname) --ignore-daemonsets; \
                  reboot; \
                  fi
              imagePullPolicy: IfNotPresent
              securityContext:
                privileged: true
          terminationGracePeriodSeconds: 0
          restartPolicy: Never
          dnsPolicy: ClusterFirst
          serviceAccountName: default
          serviceAccount: default
          nodeName: routermule
          hostNetwork: true
          hostPID: true
          hostIPC: true
          tolerations:
            - operator: Exists
          priorityClassName: system-node-critical
          priority: 2000001000
          enableServiceLinks: true
          preemptionPolicy: PreemptLowerPriority
