apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    experimental:
      http3:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    logs:
      general:
        level: INFO
    ports:
      websecure:
        http3:
          enabled: true
          advertisedPort: 443
      restic:
        port: 8444
        expose: true
        exposedPort: 444
      syncthing-udp:
        protocol: UDP
        port: 22001
        expose: true
        exposedPort: 22001
      syncthing-tcp:
        port: 22000
        expose: true
        exposedPort: 22000
      syncthing:
        protocol: UDP
        port: 21017
        expose: true
        exposedPort: 21017
    service:
      annotations:
        metallb.universe.tf/allow-shared-ip: default
        metallb.universe.tf/address-pool: default
---
#apiVersion: traefik.containo.us/v1alpha1
#kind: IngressRoute
#metadata:
#  name: http-to-https-redirect
#  namespace: kube-system
#spec:
#  entryPoints:
#    - web
#  routes:
#    - kind: Rule
#      match: PathPrefix(`/`)
#      priority: 1
#      middlewares:
#        - name: redirect-to-https
#      services:
#        - kind: TraefikService
#          name: noop@internal
#---
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: kube-system
spec:
  redirectScheme:
    scheme: https
    permanent: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: TLSOption
metadata:
  name: default
  namespace: kube-system
spec:
  minVersion: VersionTLS12
  cipherSuites:
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384   # TLS 1.2
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305    # TLS 1.2
    - TLS_AES_256_GCM_SHA384                  # TLS 1.3
    - TLS_CHACHA20_POLY1305_SHA256            # TLS 1.3
  curvePreferences:
    - CurveP521
    - CurveP384
  sniStrict: true