apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      dns:
        protocol: UDP
        port: 5353
        expose: true
        exposedPort: 53
      restic:
        port: 8444
        expose: true
        exposedPort: 444
      syncthing-udp:
        protocol: UDP
        port: 22001
        expose: true
        exposedPort: 22001
      syncthing-tcp:
        port: 22000
        expose: true
        exposedPort: 22000
      syncthing:
        protocol: UDP
        port: 21017
        expose: true
        exposedPort: 21017